### ISSUE TITLE
cc loader is not opening

### ISSUE THREAD

**Issue by shehroooo** [RedBearLab/CCLoader#1]
when i clicked to ccloader.exe  ,some kind of window appears for less than a second and then suddenly disappears. Somehow i managed to take screenshot of that...pls tell me what is this error says.

thank you in advance:)
![untitled](https://cloud.githubusercontent.com/assets/19292571/15158751/b78789d8-170a-11e6-8ed3-fccc925379d8.jpg)

**Comment by XuGuohui** [comment]
The CCLoader.exe should be executed from command line terminal, rather than by clicking it to run.

Cheers!

**Comment by shehroooo** [comment]
How ? Can u tell me pls .. As i m new to this . pls

**Comment by XuGuohui** [comment]
According to the screenshot, you should start the command line prompt first and then change the work path to where CCLoader located:
`cd Desktop\CCLoader-master\Windows`
Then type `CCLoader.exe` and press Enter to execute this program. It will print some message to guide you how to pass parameters to it.

Cheers!

**Comment by shehroooo** [comment]
Where do i place .bin file ? N how i locate the .bin file in comand prompt.

All things are going well. Thanks to your guidence ,But now the error says file is not existed or is occupied

**Comment by shehroooo** [comment]
![Uploading IMG_20160512_232218421.jpg…]()

**Comment by shehroooo** [comment]
![img_20160512_232218421](https://cloud.githubusercontent.com/assets/19292571/15225576/6b402956-1898-11e6-8bd7-c10502198d3b.jpg)

**Comment by XuGuohui** [comment]
The bin file is the one you are going to load to BLEMini and you should type this file's name with its path, either relative or absolute.

**Comment by shehroooo** [comment]
How ? Can u please show ... Thanks in advance . :)

**Comment by XuGuohui** [comment]
E.g. `CCLoader.exe 9 ..\Bin\Demo.bin 0`.

**Comment by shehroooo** [comment]
![capture1312](https://cloud.githubusercontent.com/assets/19292571/15239775/a1eb2346-18fe-11e6-8e59-90ccb86a4106.JPG)

**Comment by shehroooo** [comment]
![capture123](https://cloud.githubusercontent.com/assets/19292571/15239799/c4bed0d4-18fe-11e6-8e1c-81fb3fcd7f3d.JPG)

**Comment by shehroooo** [comment]
Thank you so much uploader for the help.....cheers :)
