### ISSUE TITLE
DD and DC

### ISSUE THREAD

**Issue by KennetZed** [RedBearLab/CCLoader#15]
I've been googling for ages! can't seem to find pin-info about this hm-11 board from ebay.

Any idea which is DD and DC on this?
(this one is broken - please disregard that)

![20180122_113132](https://user-images.githubusercontent.com/35687302/35216556-48496f6c-ff68-11e7-99c9-fa7fffb980dc.jpg)

**Comment by nullp0tr** [comment]
A view of the board from the other side might help.

**Comment by KennetZed** [comment]
You're right. A picture of the front:
![frontside](https://user-images.githubusercontent.com/35687302/35428760-2d887dce-0271-11e8-86a8-d3192001d522.jpg)

**Comment by nullp0tr** [comment]
Hmm, that doesn't look like a CC254x. A google search is telling me this is a TLSR8266, not sure how compatible it is with a CC254x.

**Comment by KennetZed** [comment]
Darn it! Seems like both a british seller and a chinese seller have fooled my friend who bought them for this project :-) 
He even purchased from two different ebay-sellers, and it seems ended up with the wrong ones twice - i now see that other sellers call these exact ones "compatible CC2541", and not the real thing.

Thank you for your help! we'll better try to purchase new ones from different sellers, and look closely at the images, to make sure we get the correct ones.

**Comment by nullp0tr** [comment]
I guess you can close the issue then:) good luck on your project!

**Comment by KennetZed** [comment]
Thank you :-)
