### ISSUE TITLE
Waiting for arduino (basically for ever)

### ISSUE THREAD

**Issue by Gohstgamer** [RedBearLab/CCLoader#17]
Hi there,

Somehow it is not working out for me. I double checked all connections. But it allways get's stuck when I run the program...
And I can't use it (the fake HM-10) as before

Greets Simon

**Comment by nullp0tr** [comment]
Are you getting "waiting for respond..."? If so: 
- CTRL-C
- Run again but with the last option for arduino type inverted (so 0 instead of 1, or vice versa)
- CTRL-C when you get same message
- Run again with correct arduino option

**Comment by Gohstgamer** [comment]
I ended up using a Mac version of it: https://github.com/hoiberg/CCLoaderX
Works perfectly and is much more responsive and even has a GUI.
